/**
 * Shared membership catalog data for both frontend and Netlify functions
 */

export const MEMBERSHIP_CATALOG = [
  // Annual Membership
  {
    id: 'annual',
    name: 'Annual Membership',
    durationLabel: 'year',
    durationMonths: 12,
    price: 20.00,
    description: 'A full year of spiritual community membership — directly supporting the Hindu Temple Project in Limerick.',
    benefits: [
      'Monthly Nama-Nakshatra Archana',
      'Annual special-occasion Archana',
      'Karpaga Vriksham leaf entry',
      'Community newsletter & event invitations',
      'Full AGM voting rights',
      'Annual report and tax receipt',
    ],
    popular: true,
    sortOrder: 1,
    cadence: 'annual',
    category: 'membership',
    subtitle: 'Core membership',
    icon: 'Crown',
    gradient: 'from-orange-500 to-amber-500',
    bgGradient: 'from-orange-50 to-amber-50',
    borderColor: 'border-orange-200',
    active: true,
  },
  // Monthly Giving Tiers
  {
    id: 'shraddha',
    name: 'Shraddha',
    durationLabel: 'month',
    durationMonths: 1,
    price: 22.00,
    description: 'Support weekly prayers and monthly community satsang.',
    benefits: [
      'Monthly Nama-Nakshatra Archana',
      'Community newsletter',
      'Satsang invitations',
    ],
    popular: false,
    sortOrder: 10,
    cadence: 'monthly',
    category: 'giving',
    subtitle: 'Faith',
    icon: 'Flame',
    gradient: 'from-orange-500 to-rose-500',
    bgGradient: 'from-orange-50 to-rose-50',
    borderColor: 'border-orange-200',
    active: true,
  },
  {
    id: 'seva',
    name: 'Seva',
    durationLabel: 'month',
    durationMonths: 1,
    price: 50.00,
    description: 'Help maintain our community hall and support weekly cultural programs.',
    benefits: [
      'All Shraddha tier benefits',
      'Monthly special puja dedication',
      'Quarterly donor report',
      'Recognition in community newsletter',
    ],
    popular: true,
    sortOrder: 11,
    cadence: 'monthly',
    category: 'giving',
    subtitle: 'Service',
    icon: 'HandCoins',
    gradient: 'from-emerald-500 to-teal-500',
    bgGradient: 'from-emerald-50 to-teal-50',
    borderColor: 'border-emerald-200',
    active: true,
  },
  {
    id: 'bhakti',
    name: 'Bhakti',
    durationLabel: 'month',
    durationMonths: 1,
    price: 100.00,
    description: 'Champion supporter of the Limerick Hindu Temple project.',
    benefits: [
      'All Seva tier benefits',
      'Founding donor recognition plaque',
      'Priority event seating',
      'Invitation to annual donor appreciation dinner',
      'Direct updates from temple committee',
    ],
    popular: false,
    sortOrder: 12,
    cadence: 'monthly',
    category: 'giving',
    subtitle: 'Devotion',
    icon: 'Star',
    gradient: 'from-violet-500 to-purple-500',
    bgGradient: 'from-violet-50 to-purple-50',
    borderColor: 'border-violet-200',
    active: true,
  },
  {
    id: 'custom',
    name: 'Custom',
    durationLabel: 'month',
    durationMonths: 1,
    price: 0,
    description: 'Give the amount that feels right for you, every month.',
    benefits: ['Benefits based on contribution', 'Flexible giving', 'Cancel any time'],
    popular: false,
    sortOrder: 13,
    cadence: 'monthly',
    category: 'giving',
    subtitle: 'Your Choice',
    icon: 'HandCoins',
    gradient: 'from-slate-600 to-slate-700',
    bgGradient: 'from-slate-50 to-gray-50',
    borderColor: 'border-slate-200',
    active: true,
  },
]
